from .landing import LandingView
from .login import LoginView
from .register import RegisterView
from .home import HomeView
from .courses import CoursesView
from .course import CourseView
from .lesson import LessonView
from .profile import ProfileView
from .test import TestView